- _target_: bmfm_targets.config.TrainingTaskConfig
  default_root_dir: "${output_directory}/${checkpoint_name}/${data_module.dataset_name}"
  max_epochs: ${max_finetuning_epochs}
  precision: "32"
  val_check_interval: 0.25
  accelerator: "gpu"
  max_steps: -1  # -1 means no limit
  tf32_mode: medium  # permitted values: "highest", "high", "medium"
  accumulate_grad_batches: 1
  freeze_encoder: false
  resume_training_from_ckpt: false
- _target_: bmfm_targets.config.TestTaskConfig
  default_root_dir: "${output_directory}/${checkpoint_name}/${data_module.dataset_name}"
  precision: 32
  accelerator: gpu
  tf32_mode: medium
  checkpoint: best
  num_bootstrap_runs: 0
  ci_method: binomial
