- _target_: bmfm_targets.config.TrainingTaskConfig
  default_root_dir: "${output_directory}/${checkpoint_name}/${dataset_name}"
  max_epochs: ${max_finetuning_epochs}
  precision: "16-mixed"
  val_check_interval: 0.25
  accelerator: "gpu"
  max_steps: -1  # -1 means no limit
  tf32_mode: medium  # permitted values: "highest", "high", "medium"
  accumulate_grad_batches: 1
  freeze_encoder: false
  resume_training_from_ckpt: false
- _target_: bmfm_targets.config.TestTaskConfig
  default_root_dir: "${output_directory}/${checkpoint_name}/${dataset_name}"
  precision: 16-mixed
  accelerator: gpu
  tf32_mode: medium
  checkpoint: last
  num_bootstrap_runs: 1
