_target_: bmfm_targets.config.TrainerConfig
batch_size: ${data_module.batch_size}
warmup_steps: 1000
weight_decay: ${model_wd}
learning_rate: ${learning_rate}
betas:
  - 0.9
  - 0.99
epsilon: 1.0e-8
lr_decay_steps: null
losses:
    - weight: 1
      label_column_name: ${label_columns[0].label_column_name}

batch_prediction_behavior: dump
lora_config: null
#   _target_: bmfm_targets.config.LoraConfigWrapper
#   target_modules:
#   - attn.Wqkv
#   - attn.Wo
#   - mlp.Wi
#   - mlp.Wo
