###################################
# GETTING STARTED WITH PRE-COMMIT #
###################################
# To start using this pre-commit file instapp pre-commit:
#   pip install pre-commit
# Install hooks:
#   pre-commit install
# Note:  Multiple changes to the same file by a hook will block git commits.
#    Therefore hooks should be added one at a time.
# Apply to all files without commiting:
#   pre-commit run --all-files
# For more info, see https://pre-commit.com/

##########
# UPDATE #
##########
# Update this file (will change version numbers of tools, which could lead to
# simultaneous changes that require manual resolution):
#   pre-commit autoupdate

#############
# CUSTOMIZE #
#############
# To customize per-hook behavior you can use:
#  1) the `args` option to pass cli args to the tool
#  2) per-tool config files such as mypy.ini, .pylintrc etc in repo root
#  3) the shared config file pyproject.toml in repo root

#############
# UNINSTALL #
#############
# pre-commit uninstall
repos:
  # default hooks provided by the pre-commit project
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  # mypy: type checking - caution this can be hard to satisfy also slow
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910-1
  #   hooks:
  #       - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.284
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [ python, pyi, jupyter ]
  # black: automatic pep8 compliance code formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
