_target_: bmfm_targets.config.SCPerformerConfig
_partial_: true
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
hidden_act: "gelu"
hidden_size: 768
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
initializer_range: 0.02
layer_norm_eps: 1e-12
kernel_type: "relu"
use_recurrent_decoding: false
kernel_epsilon: 1.0e-4
normalize_output:  true
normalization_stabilizer: 1.0e-6
num_random_features: null
regularize_feature_norms:  true
causal:  false
feature_redraw_interval: 500
classifier_dropout: 0.1
checkpoint: null