_target_: bmfm_targets.config.SCBertConfig
_partial_: true
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
hidden_act: "gelu"
hidden_size: 768
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
attention: torch
initializer_range: 0.02
layer_norm_eps: 1.0e-12
pad_token_id: 0
use_cache: true
classifier_dropout: 0.1
checkpoint: null
