- _target_: bmfm_targets.config.TrainingTaskConfig
  default_root_dir: "${working_dir}"
  max_epochs: "${max_epochs}"
  precision: 32
  val_check_interval: "${val_check_interval}"
  accelerator: "${accelerator}"
  max_steps: -1  # -1 means no limit
  tf32_mode: medium  # permitted values: "highest", "high", "medium"
  freeze_encoder: false
  resume_training_from_ckpt: false
- _target_: bmfm_targets.config.TestTaskConfig
  default_root_dir: "${working_dir}"
  precision: 32
  accelerator: "${accelerator}"
  tf32_mode: medium
  checkpoint: best
