defaults:
 - base_seq_cls

_target_: bmfm_targets.datasets.dnaseq.DNASeqCovidDataModule
max_length: 256
dataset_kwargs:
  processed_data_source: ${input_directory}/covid_prediction
  dataset_name: ${dataset_name}
