defaults:
 - base_seq_cls

_target_: bmfm_targets.datasets.dnaseq.DNASeqDrosophilaEnhancerDataModule
max_length: 80
dataset_kwargs:
  processed_data_source: ${input_directory}/drosophila_enhancer_prediction
  dataset_name: ${dataset_name}
