defaults:
 - base_seq_cls

_target_: bmfm_targets.datasets.dnaseq.DNASeqPromoterDataModule
max_length: 80
dataset_kwargs:
   processed_data_source: ${input_directory}/promoter_prediction/len_300/${fold}
   dataset_name: ${dataset_name}
