defaults:
 - base_seq_cls

_target_: bmfm_targets.datasets.dnaseq.DNASeqSpliceSiteDataModule
max_length: 80
dataset_kwargs:
   processed_data_source: ${input_directory}/splice_site_prediction/${fold}
   dataset_name: ${dataset_name}
