defaults:
  - data_module: sceval_default
  - tokenizer: all_genes
  - fields: genes_expressions_wced
  - trainer: default
  - task: train
  - model: scbert
  - label_columns: default
  - _self_
seed:
  seed_value: 1234

trainer:
  losses:
    - name: focal
      label_column_name: ${label_columns[0].label_column_name}
      focal_gamma: 3
  # for rda models this should be set to `first_token`, for multitask 'pooling_layer' or 'mean_pooling'
  pooling_method: pooling_layer
  batch_prediction_behavior: track

track_clearml:
  project_name: "bmfm-targets/evaluate/${checkpoint_name}"
  task_name: "${data_module.dataset_name}_ft"
  continue_last_task: False

# to adapt all of the dataset input to the ckpt modify this section
# in general it should match the pretraining config except for masking settings
data_module:
  max_length: 1024
  batch_size: 8
  # rda_transform: auto_align
  # limit genes is modified per dataset to handle mouse
  pad_zero_expression_strategy: batch_wise
  collation_strategy: sequence_classification


max_finetuning_epochs: 2

dataset_name: "" # do not modify, set by script
checkpoint_path: ""
checkpoint_name: multitask_cellxgene_v2
# checkpoint_name: multitask_cellxgene
output_directory: ""
