_target_: bmfm_targets.config.SCModernBertConfig
_partial_: true
classifier_pooling: "mean"
num_hidden_layers: 22
#num_attention_heads: 12
#intermediate_size: 3072
hidden_activation: "gelu"
hidden_size: 768
max_position_embeddings: ${model_pe}
embedding_dropout: 0.1
attention_dropout: 0.1
classifier_dropout: 0.1
norm_eps: 1e-12
pad_token_id: 2
use_cache: true
checkpoint: ${checkpoint_path}
