defaults:
  - data_module: dnaeval_default
  - tokenizer: ref2vec
  - fields: dna_chunks
  - trainer: default
  - task: train_and_test
  - model: modernbert
  - label_columns: dnaeval_default
  - _self_

seed:
  seed_value: 1234

model:
  checkpoint: null

data_module:
  max_length: 32
  data_dir: /PATH/TO/DATA/
  processed_name: processed_data
  batch_size: 20
  limit_genes: protein_coding #could be null, protein_coding, or tokenizer
  transform_datasets: false

trainer:
  learning_rate: 1.0e-5
  losses:
    - name: cross_entropy
      label_column_name: ${label_column_name}

label_column_name: celltype
output_directory: /tmp
accelerator: gpu
val_check_interval: 0.5
max_epochs: 20
accumulate_grad_batches: 5
checkpoints_every_n_train_steps: 5000
