defaults:
  - data_module: zheng68k
  - task: predict
  - _self_

seed:
  seed_value: 1234

data_module:
  max_length: 32
  data_dir: ${oc.env:BMFM_TARGETS_ZHENG68K_DATA}
  batch_size: 20

task:
  checkpoint: null

output_directory: /tmp