defaults:
  - data_module: base_seq_cls
  - task: test
  - _self_

seed:
  seed_value: 1234

data_module:
  max_length: 32
  data_dir: /PATH/TO/DATA/
  processed_name: processed_data
  limit_genes: protein_coding #could be null, protein_coding, or tokenizer

task:
  checkpoint: null
  num_bootstrap_runs: 1

output_directory: /tmp
accelerator: gpu
output_embeddings: true
output_predictions: true