defaults:
 - base_seq_cls

_target_: bmfm_targets.datasets.hbones.HBonesDataModule
_partial_: true
num_workers: 8
mlm: false
limit_genes: protein_coding
shuffle: true
transform_datasets: false
data_dir: /dccstor/bmfm-targets/data/omics/transcriptome/scRNA/finetune/hBones
processed_name: processed_rawcount
dataset_kwargs:
  split_column_name: split_cross
  label_columns:
  - celltype
label_column_name: celltype
dataset_name: hbones
batch_column_name: donor #batch
log_normalize_transform: true
